version: '2.2'
services:
    mongo:
        image: mongo:4.0
        container_name: 'mongo'
        ports:
            - '27017:27017'
        env_file:
            ./environment/db.env
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    portal-noticias:
        container_name: portal-noticias
        build: .
        command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py loaddata initial.json
            && python manage.py createsuperuser --noinput
            && python manage.py runserver 0.0.0.0:8000"
        ports:
            - '8000:8000'
        env_file:
            ./environment/portal.env
        volumes:
            - .:/portal-noticias
        depends_on:
            - mongo